/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.kacperbak.picocli.playground;

import de.kacperbak.picocli.playground.commands.HelloCommand;
import picocli.CommandLine;

public class App {

    public static void main(String[] args) {
        int exitCode = new CommandLine(new HelloCommand()).execute(args);
        System.exit(exitCode);
    }
}
